packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@types/node": ^24
  typescript: ^5.9.3
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
  drizzle-orm: ^0.45.2
  drizzle-kit: ^0.31.10
  zod: ^4.4.3
  '@hono/zod-validator': ^0.8.0
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
allowBuilds:
  esbuild: true
  sharp: false
  workerd: true
patchedDependencies:
  "@ts-76/inertia-hono-jsx@0.2.0": patches/@ts-76__inertia-hono-jsx@0.2.0.patch
