packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@types/node": ^24
  typescript: ^5.9.3
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
  drizzle-orm: ^0.45.2
  drizzle-kit: ^0.31.10
  zod: ^4.4.3
  "@hono/zod-validator": ^0.8.0
  tailwindcss: ^4.3.0
  "@tailwindcss/vite": ^4.3.0
  better-auth: ^1.6.11
  "@better-auth/cli": ^1.4.21
  "@better-auth/drizzle-adapter": ^1.6.11
  d3-scale: ^4.0.2
  "@types/d3-scale": ^4.0.9
  "@clack/prompts": ^1.4.0
  picocolors: ^1.1.1
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
allowBuilds:
  "@prisma/client": set this to true or false
  better-sqlite3: set this to true or false
  esbuild: true
  sharp: false
  workerd: true
