// AUTO-GENERATED by @hono/inertia/vite. Do not edit.
import type app from './index'

export type PageName = 'Accounts/Edit' | 'Accounts/Index' | 'Categories/Edit' | 'Categories/Index' | 'Home' | 'Login' | 'Signup'

declare module '@hono/inertia' {
  interface InertiaPages {
    'Accounts/Edit': unknown
    'Accounts/Index': unknown
    'Categories/Edit': unknown
    'Categories/Index': unknown
    'Home': unknown
    'Login': unknown
    'Signup': unknown
  }
  interface AppRegistry {
    app: typeof app
  }
}

export type { PageProps } from '@hono/inertia'
