// AUTO-GENERATED by @hono/inertia/vite. Do not edit.
import type app from './index'

export type PageName = 'Home' | 'Login' | 'Signup' | 'Story' | 'Submit'

declare module '@hono/inertia' {
  interface InertiaPages {
    'Home': unknown
    'Login': unknown
    'Signup': unknown
    'Story': unknown
    'Submit': unknown
  }
  interface AppRegistry {
    app: typeof app
  }
}

export type { PageProps } from '@hono/inertia'
