// AUTO-GENERATED by @hono/inertia/vite. Do not edit.
import type app from './index'

export type PageName = 'Adapter/FormDemo' | 'Adapter/HeadKeys' | 'Adapter/InfiniteScrollDemo' | 'Adapter/RealtimeDemo' | 'Home' | 'Users/Index' | 'Users/New' | 'Users/Show'

declare module '@hono/inertia' {
  interface InertiaPages {
    'Adapter/FormDemo': unknown
    'Adapter/HeadKeys': unknown
    'Adapter/InfiniteScrollDemo': unknown
    'Adapter/RealtimeDemo': unknown
    'Home': unknown
    'Users/Index': unknown
    'Users/New': unknown
    'Users/Show': unknown
  }
  interface AppRegistry {
    app: typeof app
  }
}

export type { PageProps } from '@hono/inertia'
